#lang racket
(require racket/draw)

(define ace_of_clubs (read-bitmap "images/ace_of_clubs.png"))
(define 2_of_clubs (read-bitmap "images/2_of_clubs.png"))
(define 3_of_clubs (read-bitmap "images/3_of_clubs.png"))
(define 4_of_clubs (read-bitmap "images/4_of_clubs.png"))
(define 5_of_clubs (read-bitmap "images/5_of_clubs.png"))
(define 6_of_clubs (read-bitmap "images/6_of_clubs.png"))
(define 7_of_clubs (read-bitmap "images/7_of_clubs.png"))
(define 8_of_clubs (read-bitmap "images/8_of_clubs.png"))
(define 9_of_clubs (read-bitmap "images/9_of_clubs.png"))
(define 10_of_clubs (read-bitmap "images/10_of_clubs.png"))
(define jack_of_clubs (read-bitmap "images/jack_of_clubs.png"))
(define queen_of_clubs (read-bitmap "images/queen_of_clubs.png"))
(define king_of_clubs (read-bitmap "images/king_of_clubs.png"))

(define ace_of_diamonds (read-bitmap "images/ace_of_diamonds.png"))
(define 2_of_diamonds (read-bitmap "images/2_of_diamonds.png"))
(define 3_of_diamonds (read-bitmap "images/3_of_diamonds.png"))
(define 4_of_diamonds (read-bitmap "images/4_of_diamonds.png"))
(define 5_of_diamonds (read-bitmap "images/5_of_diamonds.png"))
(define 6_of_diamonds (read-bitmap "images/6_of_diamonds.png"))
(define 7_of_diamonds (read-bitmap "images/7_of_diamonds.png"))
(define 8_of_diamonds (read-bitmap "images/8_of_diamonds.png"))
(define 9_of_diamonds (read-bitmap "images/9_of_diamonds.png"))
(define 10_of_diamonds (read-bitmap "images/10_of_diamonds.png"))
(define jack_of_diamonds (read-bitmap "images/jack_of_diamonds.png"))
(define queen_of_diamonds (read-bitmap "images/queen_of_diamonds.png"))
(define king_of_diamonds (read-bitmap "images/king_of_diamonds.png"))

(define ace_of_hearts (read-bitmap "images/ace_of_hearts.png"))
(define 2_of_hearts (read-bitmap "images/2_of_hearts.png"))
(define 3_of_hearts (read-bitmap "images/3_of_hearts.png"))
(define 4_of_hearts (read-bitmap "images/4_of_hearts.png"))
(define 5_of_hearts (read-bitmap "images/5_of_hearts.png"))
(define 6_of_hearts (read-bitmap "images/6_of_hearts.png"))
(define 7_of_hearts (read-bitmap "images/7_of_hearts.png"))
(define 8_of_hearts (read-bitmap "images/8_of_hearts.png"))
(define 9_of_hearts (read-bitmap "images/9_of_hearts.png"))
(define 10_of_hearts (read-bitmap "images/10_of_hearts.png"))
(define jack_of_hearts (read-bitmap "images/jack_of_hearts.png"))
(define queen_of_hearts (read-bitmap "images/queen_of_hearts.png"))
(define king_of_hearts (read-bitmap "images/king_of_hearts.png"))

(define ace_of_spades (read-bitmap "images/ace_of_spades.png"))
(define 2_of_spades (read-bitmap "images/2_of_spades.png"))
(define 3_of_spades (read-bitmap "images/3_of_spades.png"))
(define 4_of_spades (read-bitmap "images/4_of_spades.png"))
(define 5_of_spades (read-bitmap "images/5_of_spades.png"))
(define 6_of_spades (read-bitmap "images/6_of_spades.png"))
(define 7_of_spades (read-bitmap "images/7_of_spades.png"))
(define 8_of_spades (read-bitmap "images/8_of_spades.png"))
(define 9_of_spades (read-bitmap "images/9_of_spades.png"))
(define 10_of_spades (read-bitmap "images/10_of_spades.png"))
(define jack_of_spades (read-bitmap "images/jack_of_spades.png"))
(define queen_of_spades (read-bitmap "images/queen_of_spades.png"))
(define king_of_spades (read-bitmap "images/king_of_spades.png"))

(define black_joker (read-bitmap "images/black_joker.png"))
(define red_joker (read-bitmap "images/red_joker.png"))
(define crazyeights_logo (read-bitmap "images/crazyeights-logo.png"))


(provide (all-defined-out))